### ISSUE TITLE
Suggestion about switching to test environment dynamically

### ISSUE THREAD

**Issue by kagan94** [fieldnation/fieldnation-sdk-php#10]
It would be great if you could add switching to test environment (stable.fieldnation.com instead of api.fieldnation.com) maybe through the **ClassMapFactoryInterface**.

Currently we need to go to the file "\vendor\fieldnation\fieldnation-sdk\src\FieldNation\SoapClient.php" and replace the constant `SOAP_API_BASE`.

**Comment by evan-duncan** [comment]
@kagan94 You can switch the environment through your credentials. One reason we didn't put the option in the ClassMapFactory because the environment isn't really coupled to the concrete classes -- it's tied to your creds. I will add a section README to address this issue.

```php
<?php
$fnCompanyId = $_ENV['FIELD_NATION_COMPANY_ID'];
$fnApiKey = $_ENV['FIELD_NATION_API_KEY'];
$credentials = new \FieldNation\LoginCredentials($fnCompanyId, $fnApiKey, $fnEffectiveUser);
$credentials->setEnvironment("https://stable.fieldnation.com");
$fn = new \FieldNation\SDK($credentials);
```
