### ISSUE TITLE
Need to cut a new release since fixing the $label bug (renaming $label variable to $labelClass in SoapClient)

### ISSUE THREAD

**Issue by jacobbeasley** [fieldnation/fieldnation-sdk-php#14]
I think we'll just make our composer.json check out the specific commit that fixed the bug, but it would be nice if you cut a release since fixing it. 

Also, I have to believe a codelinter could catch variable name re-use like this. It's a nasty thing in loosely typed languages like PHP... might be worth considering adding it to your build pipieline. 

Thanks for fixing the issue! It is a huge help to us because it basically broke the API after a job was in progress because if any labels were present it would crash the API. We are running it and testing in prod. Hoping to launch our product shortly and this API has been very helpful!

**Comment by jacobbeasley** [comment]
Also, on a side note, forget what I'm saying about linting. I was digging into phpcs and didn't find a quick-and-easy way to turn on some kind of a style check around variable re-use and re-assignment... 

(https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties)

Admittedly, I don't know much about phpcs. Haven't been doing much PHP lately...

**Comment by evan-duncan** [comment]
We're working on it, @jacobbeasly. The original intent was to fix the other issues before cutting a release, but time has run away on this one. Thanks for opening an issue.

Side note, we do lint everything but I'm not sure if our linter would have a reasonable way of detecting this. For what it's worth, more/better unit tests should have made the problem obvious.

**Comment by jacobbeasley** [comment]
Agreed. Thanks for the update! The API works great!

On Oct 3, 2017 7:58 AM, "Evan Duncan" <notifications@github.com> wrote:

We're working on it, @jacobbeasly. The original intent was to fix the other
issues before cutting a release, but time has run away on this one. Thanks
for opening an issue.

Side note, we do lint everything but I'm not sure if our linter would have
a reasonable way of detecting this. For what it's worth, more/better unit
tests should have made the problem obvious.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fieldnation/fieldnation-sdk-php/issues/14#issuecomment-333833305>,
or mute the thread

**Comment by evan-duncan** [comment]
@jacobbeasley 1.1.0 has been release with this fix.

https://packagist.org/packages/fieldnation/fieldnation-sdk#1.1.0
