### ISSUE TITLE
Bug with processing labels

### ISSUE THREAD

**Issue by kagan94** [fieldnation/fieldnation-sdk-php#9]
Hello.
Here is another bug:
[../src/FieldNation/SoapClient.php - Lines #193-195](https://github.com/fieldnation/fieldnation-sdk-php/blob/develop/src/FieldNation/SoapClient.php#L194)

You convert ```$label``` variable to string and try to use this var later. However, it should be an object, not a string (classMapFactory->getLabel() returns string). I mean you reassigned this variable by mistake as it is already used in `foreach ($wo->labels as $label)`.

Possible solution:
```
$labelClass = $this->classMapFactory->getLabel();
$labelObj = new $labelClass();
```

**Comment by evan-duncan** [comment]
@kagan94 That looks like an appropriate fix. If you have time to open a PR to fix it, that would be great.
